// <auto-generated />
using System;
using FleetManagement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20261003164022_InitialUuidV7")]
    partial class InitialUuidV7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetManagement.Domain.Modules.Access.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("security_version");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "security");
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.Fine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId", "Date");

                    b.ToTable("fines", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_fines_values", "amount >= 0 AND points >= 0");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.LicenseExpiration", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean")
                        .HasColumnName("expired");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Date");

                    b.ToTable("license_expirations", "operations");
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.Maintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("VehicleId", "Date");

                    b.ToTable("maintenance_records", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_records_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.MaintenancePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<int?>("IntervalMileage")
                        .HasColumnType("integer")
                        .HasColumnName("interval_mileage");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LastCompletedMileage")
                        .HasColumnType("integer")
                        .HasColumnName("last_completed_mileage");

                    b.Property<DateOnly?>("LastCompletedOn")
                        .HasColumnType("date")
                        .HasColumnName("last_completed_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_due_date");

                    b.Property<int?>("NextDueMileage")
                        .HasColumnType("integer")
                        .HasColumnName("next_due_mileage");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("NextDueDate")
                        .HasFilter("is_active = true AND next_due_date IS NOT NULL");

                    b.HasIndex("VehicleId", "IsActive");

                    b.ToTable("maintenance_plans", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_maintenance_plans_interval", "((interval_days IS NULL AND next_due_date IS NULL) OR (interval_days > 0 AND next_due_date IS NOT NULL)) AND ((interval_mileage IS NULL AND next_due_mileage IS NULL) OR (interval_mileage > 0 AND next_due_mileage >= 0)) AND (interval_days IS NOT NULL OR interval_mileage IS NOT NULL)");

                            t.HasCheckConstraint("ck_maintenance_plans_revision", "revision > 0");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.MovementChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("BodyOk")
                        .HasColumnType("boolean")
                        .HasColumnName("body_ok");

                    b.Property<DateTime>("CheckedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at_utc");

                    b.Property<bool>("FluidsOk")
                        .HasColumnType("boolean")
                        .HasColumnName("fluids_ok");

                    b.Property<bool>("LightsOk")
                        .HasColumnType("boolean")
                        .HasColumnName("lights_ok");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("phase");

                    b.Property<bool>("TiresOk")
                        .HasColumnType("boolean")
                        .HasColumnName("tires_ok");

                    b.HasKey("Id");

                    b.HasIndex("MovementId", "Phase")
                        .IsUnique();

                    b.ToTable("movement_checklists", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_movement_checklists_phase", "phase IN ('departure', 'arrival')");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.Refueling", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<decimal>("Liters")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("liters");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer")
                        .HasColumnName("mileage");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId", "Date");

                    b.ToTable("refuelings", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_refuelings_values", "mileage >= 0 AND amount >= 0 AND liters > 0");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.VehicleMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArrivalUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("arrival_utc");

                    b.Property<DateTime>("DepartureUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("departure_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime?>("ExpectedReturnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_return_utc");

                    b.Property<int?>("FinalMileage")
                        .HasColumnType("integer")
                        .HasColumnName("final_mileage");

                    b.Property<int>("InitialMileage")
                        .HasColumnType("integer")
                        .HasColumnName("initial_mileage");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpectedReturnUtc")
                        .HasFilter("arrival_utc IS NULL AND expected_return_utc IS NOT NULL");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasFilter("reservation_id IS NOT NULL");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasFilter("arrival_utc IS NULL");

                    b.HasIndex("DriverId", "DepartureUtc");

                    b.ToTable("vehicle_movements", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_movements_arrival", "(arrival_utc IS NULL) = (final_mileage IS NULL) AND (arrival_utc IS NULL OR arrival_utc >= departure_utc)");

                            t.HasCheckConstraint("ck_vehicle_movements_expected_return", "expected_return_utc IS NULL OR expected_return_utc >= departure_utc");

                            t.HasCheckConstraint("ck_vehicle_movements_mileage", "initial_mileage >= 0 AND (final_mileage IS NULL OR final_mileage >= initial_mileage)");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.VehicleReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid")
                        .HasColumnName("driver_id");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "StartUtc");

                    b.HasIndex("VehicleId", "StartUtc");

                    b.ToTable("vehicle_reservations", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_reservations_dates", "end_utc > start_utc");

                            t.HasCheckConstraint("ck_vehicle_reservations_revision", "revision > 0");

                            t.HasCheckConstraint("ck_vehicle_reservations_status", "status IN ('Confirmed', 'InUse', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.VehicleStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_utc");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_utc");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "StartUtc");

                    b.ToTable("vehicle_statuses", "operations", t =>
                        {
                            t.HasCheckConstraint("ck_vehicle_statuses_dates", "end_utc IS NULL OR end_utc >= start_utc");
                        });
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Registrations.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("LicenseCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("license_category");

                    b.Property<DateOnly>("LicenseExpiration")
                        .HasColumnType("date")
                        .HasColumnName("license_expiration");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("drivers", "registrations");
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Registrations.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Chassis")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("chassis");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("model");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("plate");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("renavam");

                    b.HasKey("Id");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("vehicles", "registrations");
                });

            modelBuilder.Entity("FleetManagement.Infrastructure.Persistence.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("ActorUsername")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor_username");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("changes_json");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_name");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("audit_entries", "security");
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.Fine", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.LicenseExpiration", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.Maintenance", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Operations.MaintenancePlan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.MaintenancePlan", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.MovementChecklist", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Operations.VehicleMovement", null)
                        .WithMany()
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.Refueling", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.VehicleMovement", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetManagement.Domain.Modules.Operations.VehicleReservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.VehicleReservation", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManagement.Domain.Modules.Operations.VehicleStatus", b =>
                {
                    b.HasOne("FleetManagement.Domain.Modules.Registrations.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
