// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuemPegouOVeiculo.Infrastructure.Persistence;

#nullable disable

namespace QuemPegouOVeiculo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260928004539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Cadastros.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("CategoriaCnh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("categoria_cnh");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnh");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<DateOnly>("VencimentoCnh")
                        .HasColumnType("date")
                        .HasColumnName("vencimento_cnh");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("motoristas", "cadastros");
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Cadastros.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("chassi");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("placa");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("renavam");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculos", "cadastros");
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.Abastecimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Litros")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("litros");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId", "Data");

                    b.ToTable("abastecimentos", "operacoes", t =>
                        {
                            t.HasCheckConstraint("ck_abastecimentos_valores", "quilometragem >= 0 AND valor >= 0 AND litros > 0");
                        });
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId", "Data");

                    b.ToTable("manutencoes", "operacoes", t =>
                        {
                            t.HasCheckConstraint("ck_manutencoes_valor", "valor >= 0");
                        });
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.MovimentacaoVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ChegadaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("chegada_utc");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int?>("KmFinal")
                        .HasColumnType("integer")
                        .HasColumnName("km_final");

                    b.Property<int>("KmInicial")
                        .HasColumnType("integer")
                        .HasColumnName("km_inicial");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<DateTime>("SaidaUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saida_utc");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId")
                        .IsUnique()
                        .HasFilter("chegada_utc IS NULL");

                    b.HasIndex("MotoristaId", "SaidaUtc");

                    b.ToTable("movimentacoes", "operacoes", t =>
                        {
                            t.HasCheckConstraint("ck_movimentacoes_chegada", "(chegada_utc IS NULL) = (km_final IS NULL) AND (chegada_utc IS NULL OR chegada_utc >= saida_utc)");

                            t.HasCheckConstraint("ck_movimentacoes_km", "km_inicial >= 0 AND (km_final IS NULL OR km_final >= km_inicial)");
                        });
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.Multa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<int>("Pontos")
                        .HasColumnType("integer")
                        .HasColumnName("pontos");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("VeiculoId", "Data");

                    b.ToTable("multas", "operacoes", t =>
                        {
                            t.HasCheckConstraint("ck_multas_valores", "valor >= 0 AND pontos >= 0");
                        });
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.StatusVeiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descricao");

                    b.Property<DateTime?>("FimUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim_utc");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_utc");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId", "InicioUtc");

                    b.ToTable("status_veiculos", "operacoes", t =>
                        {
                            t.HasCheckConstraint("ck_status_veiculos_datas", "fim_utc IS NULL OR fim_utc >= inicio_utc");
                        });
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.VencimentoCnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int>("MotoristaId")
                        .HasColumnType("integer")
                        .HasColumnName("motorista_id");

                    b.Property<bool>("Vencido")
                        .HasColumnType("boolean")
                        .HasColumnName("vencido");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId", "Data");

                    b.ToTable("vencimentos_cnh", "operacoes");
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.Abastecimento", b =>
                {
                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Motorista", null)
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.Manutencao", b =>
                {
                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.MovimentacaoVeiculo", b =>
                {
                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Motorista", null)
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.Multa", b =>
                {
                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Motorista", null)
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.StatusVeiculo", b =>
                {
                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Veiculo", null)
                        .WithMany()
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuemPegouOVeiculo.Domain.Modules.Operacoes.VencimentoCnh", b =>
                {
                    b.HasOne("QuemPegouOVeiculo.Domain.Modules.Cadastros.Motorista", null)
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
